version: '3'
services:
  app:
    build: .
    volumes: 
      - .:/usr/src/app
    container_name: docker-node-tut
    restart: always
    ports: 
      - 4026:3000
    command: bash -c /usr/src/app/start.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # env_file: .env